services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    networks:
      - goexpert-network
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    networks:
      - goexpert-network
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - goexpert-network
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel/otel-collector-config.yaml"]
    networks:
      - goexpert-network
    volumes:
      - ./.docker:/etc/otel
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: orchestrator
    container_name: goexpert-orchestrator
    ports:
      - "8080:8080"
    environment:
      - WEATHER_SECRET_KEY=${WEATHER_SECRET_KEY:-f0b7cd19ad1841aeb40192648250906}
      - ORCHESTRATOR_PORT=8080
      - OTEL_SERVICE_NAME=orchestrator
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - goexpert-network
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector

  input-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: input
    container_name: goexpert-input-service
    ports:
      - "8081:8081"
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8080
      - INPUT_SERVICE_A_PORT=8081
      - OTEL_SERVICE_NAME=input-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - goexpert-network
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector


networks:
  goexpert-network:
    driver: bridge
